#CI workflow to build, test, and lint the CURD app on push or pull request

name: CI pipeline
on: 
  push: 
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checking if the code in repo if it is feasible
      - name: checkout code
        uses: actions/checkout@v4

      #CLIENT (Frontend)
      - name: Setup Node.js for CLIENT
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./CLIENT/package-lock.json

      - name: Install CLIENT dependencies
        working-directory: ./CLIENT
        run: npm ci

      - name: Lint CLIENT
        working-directory: ./CLIENT
        run: npm run lint

      - name: Build CLIENT
        working-directory: ./CLIENT
        run: npm run build


        #SERVER (BACKEND)
      - name: Setup Node.js for SERVER
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./SERVER/package-lock.json

      - name: Install SERVER dependencies
        working-directory: ./SERVER
        run: npm ci

      - name: Lint SERVER
        working-directory: ./SERVER
        run: npm run lint

      # - name: Build SERVER
      #   working-directory: ./SERVER
      #   run: npm run build



  